baseURL = "https://victoryluode.netlify.app/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en"
# 网站语言, 仅在这里 CN 大写
languageCode = "en"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "VictoryLuode"
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.2.X"
  # 网站默认主题 ("light", "dark", "black", "auto")
  defaultTheme = "dark"
  images = ["avatar.webp"]
#··················································
[author]
    name = "VictoryLuode"
    email = "victoryluode@outlook.com"
    link = "https://www.artstation.com/victoryluode"
    avatar = "avatar.webp"
    gravatarEmail = "victoryluode@outlook.com"
#··················································
[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "BLOG"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = "Post"
    weight = 1
    [[menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 2
# ··················································
[params.header.title]
          # URL of the LOGO
          # LOGO 的 URL
          logo = "V1.webp"
          # title name
          # 标题名称
          name = ""
          # you can add extra information before the name (HTML format is supported), such as icons
          # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
          pre = ""
          # you can add extra information after the name (HTML format is supported), such as icons
          # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
          post = ""
          # whether to use typeit animation for title name
          # 是否为标题显示打字机动画
          typeit = false
# ··················································

[params.home.profile]
  # Gravatar 邮箱, 用于优先在主页显示的头像
  gravatarEmail = ""
  # 主页显示头像的 URL
  avatarURL = "avatar.webp"

  title = "VictoryLuode"
  subtitle = "即将毕业的学生仔"

  typeit = true
  social = true

  disclaimer = "有时间我会把整理的有用信息放在下面"
[params.social]
  Artstation = "VictoryLuode"
  twitter = "VictoryLuode"
  Instagram = "victoryluode"
  Bilibili = "176090455"
  QQGroup = ""
  Youtubechannel = "UCZeWmv1zRtoqXdXiacofL7Q"
  Weibo = "6430541796"
  Behance = "VictoryLuode"
  Email = "victoryluode@outlook.com"


[params.home.posts]
  enable = true
# ··················································
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia", "fuse")
    type = "fuse"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # DoIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # DoIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # DoIt 新增 | 0.2.12 https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
# ··················································
      [params.page.share]
        enable = true
        Twitter = true
        Facebook = true
        Linkedin = false
        Whatsapp = false
        Line = true
        Instapaper = false
        Pocket = false
        Digg = false
        Stumbleupon = false
        Flipboard = false
        Weibo = true
        Telegram = true
# ··················································
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = ''
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = false
  # Hosted on (HTML format is supported)
  # 托管服务信息 (支持 HTML 格式)
  # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
  hostedOn = ''
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2019
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
